import { useEffect, useState } from 'react';
import { Download, Globe, Link, Monitor } from 'lucide-react';
import { api, errorText, isNative } from './api';
import { Badge, ErrorNotice, Field, Modal } from './components';
interface BrowserStatus { available?: boolean; dependency_available?: boolean; message?: string; running?: boolean; connected_tabs?: { id?: number; tab_id?: number; title?: string; url?: string }[]; extension_available?: boolean; installation?: { state: string; progress?: string[]; error?: string }; }
export function BrowserSettings({ notify }: { notify: (message: string) => void }) {
  const [status, setStatus] = useState<BrowserStatus>({}); const [error, setError] = useState(''); const [register, setRegister] = useState(false); const [extensionId, setExtensionId] = useState(''); const [executable, setExecutable] = useState(''); const [busy, setBusy] = useState(false);
  async function refresh() { try { setStatus(await api<BrowserStatus>('browser_status')); setError(''); } catch (e) { setError(errorText(e)); } }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (status.installation?.state !== 'downloading') return; const timer = setInterval(() => void refresh(), 1000); return () => clearInterval(timer); }, [status.installation?.state]);
  return <><h2>Browser tools</h2><section className="settings-card"><div className="runtime-description"><Globe size={24} /><div><strong>Isolated browser</strong><p>{status.message || 'Checking browser availability…'}</p></div><Badge>{status.available ? 'Ready' : 'Setup'}</Badge></div><div className="runtime-controls"><button className="secondary" disabled={!status.dependency_available || status.installation?.state === 'downloading'} onClick={() => void api('browser_install').then(() => { notify('Chromium installation started.'); void refresh(); }).catch(e => notify(errorText(e)))}><Download size={14} />{status.installation?.state === 'downloading' ? 'Installing…' : status.available ? 'Verify installation' : 'Install browser'}</button></div>{status.installation?.progress?.length ? <details className="runtime-output" open={status.installation.state === 'downloading'}><summary>Installation output</summary><pre>{status.installation.progress.slice(-12).join('\n')}</pre></details> : null}{status.installation?.error && <ErrorNotice error={status.installation.error} />}</section><h2>Connected Chrome / Edge tabs</h2><section className="settings-card"><div className="runtime-description"><Monitor size={24} /><div><strong>Optional browser extension</strong><p>Connect only the tabs you select in the Forge extension. Native messaging keeps other tabs outside the agent's view.</p></div></div>{status.connected_tabs?.map((tab, index) => <div className="provider-row" key={tab.id || tab.tab_id || index}><Link size={15} /><div><strong>{tab.title || 'Connected tab'}</strong><small>{tab.url}</small></div><Badge>Connected</Badge></div>)}<button className="card-footer-button" disabled={!isNative()} onClick={() => { setRegister(true); setError(''); }}><Link size={14} />Connect extension host</button></section>{error && <ErrorNotice error={error} />}
    {register && <Modal title="Connect the browser extension" close={() => setRegister(false)}><p className="muted">Load the included browser-extension folder from Chrome or Edge's Extensions page, then copy its extension ID.</p><form onSubmit={e => { e.preventDefault(); setBusy(true); void api('browser_host_register', { extension_id: extensionId, host_executable: executable }).then(() => { notify('Extension host registered. Use the Forge extension to connect a tab.'); setRegister(false); void refresh(); }).catch(e => setError(errorText(e))).finally(() => setBusy(false)); }}><Field label="Extension ID"><input required autoFocus pattern="[a-p]{32}" value={extensionId} onChange={e => setExtensionId(e.target.value.trim())} placeholder="32-character extension ID" /></Field><Field label="Forge native host executable"><input required value={executable} onChange={e => setExecutable(e.target.value)} placeholder="Absolute path to forge-browser-host.exe" /></Field>{error && <ErrorNotice error={error} />}<footer><button className="primary" disabled={busy}>{busy ? 'Registering…' : 'Register host'}</button></footer></form></Modal>}
  </>;
}
export function PairBrowserSettings() {
  const [pairing, setPairing] = useState<{ code: string; expires_in: number; url?: string } | null>(null); const [error, setError] = useState('');
  if (!isNative()) return <div className="setting-row"><div><span>Browser session</span><small>This browser is paired with the local coordinator.</small></div><button className="text-button" onClick={() => void api('unpair').then(() => location.reload())}>Unpair</button></div>;
  return <><div className="setting-row"><div><span>Pair a browser</span><small>Use the same workspace in a local browser tab.</small></div><button className="secondary" onClick={() => void api<typeof pairing>('pair_browser').then(setPairing).catch(e => setError(errorText(e)))}>Generate code</button></div>{pairing && <div className="pairing-code"><strong>{pairing.code}</strong><small>Single use · Expires in {Math.round(pairing.expires_in / 60)} minutes</small>{pairing.url && <a href={pairing.url} target="_blank" rel="noopener noreferrer">Open local workspace</a>}</div>}{error && <ErrorNotice error={error} />}</>;
}
