import { useEffect, useState } from 'react';
import { ArrowLeft, ArrowRight, Download, Globe, Link, Monitor, RotateCw, X } from 'lucide-react';
import { api, errorText, isNative } from './api';
import { Badge, ErrorNotice, Field, IconButton, Modal } from './components';
interface NativeBrowserStatus { available?: boolean; running?: boolean; loading?: boolean; engine?: string; url?: string; title?: string; message?: string; capabilities?: string[]; }
interface BrowserStatus { default_backend?: 'native' | 'isolated'; native?: NativeBrowserStatus; isolated?: { available?: boolean; dependency_available?: boolean; running?: boolean; message?: string; installation?: { state: string; progress?: string[]; error?: string } }; available?: boolean; dependency_available?: boolean; message?: string; running?: boolean; connected_tabs?: { id?: number | string; tab_id?: number | string; title?: string; url?: string }[]; extension_available?: boolean; installation?: { state: string; progress?: string[]; error?: string }; }
export function BrowserSettings({ notify }: { notify: (message: string) => void }) {
  const [status, setStatus] = useState<BrowserStatus>({}); const [error, setError] = useState(''); const [register, setRegister] = useState(false); const [extensionId, setExtensionId] = useState(''); const [executable, setExecutable] = useState(''); const [busy, setBusy] = useState(false); const [address, setAddress] = useState('');
  async function refresh(isolated = false) { try { const result = await api<BrowserStatus>('browser_status', isolated ? { backend: 'isolated' } : {}); setStatus(previous => ({ ...previous, ...result, native: result.native || previous.native })); setError(''); } catch (e) { setError(errorText(e)); } }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if ((status.isolated?.installation || status.installation)?.state !== 'downloading') return; const timer = setInterval(() => void refresh(true), 1000); return () => clearInterval(timer); }, [status.isolated?.installation?.state, status.installation?.state]);
  useEffect(() => { if (!status.native?.running) return; const timer = setInterval(() => void refresh(), 3000); return () => clearInterval(timer); }, [status.native?.running]);
  useEffect(() => { if (status.native?.url && status.native.url !== 'about:blank') setAddress(status.native.url); }, [status.native?.url]);
  async function nativeAction(action: string, data: Record<string, unknown> = {}) { setBusy(true); setError(''); try { if (action !== 'browser_native_close') window.dispatchEvent(new CustomEvent('forge:browser-open')); await api(action, data); await refresh(); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  const nativeBrowser = status.native; const isolated = status.isolated || (status.default_backend !== 'native' ? status : {});
  return <><h2>Forge browser</h2><section className="settings-card native-browser-card"><div className="runtime-description"><Globe size={25} /><div><strong>Built-in browser</strong><p>{nativeBrowser?.message || (isNative() ? 'Checking Windows browser availability…' : 'Open Forge on Windows to use its built-in browser.')}</p></div><Badge tone={nativeBrowser?.running ? 'accent' : ''}>{nativeBrowser?.loading ? 'Loading' : nativeBrowser?.running ? 'Open' : nativeBrowser?.available ? 'Ready' : 'Unavailable'}</Badge></div><p className="card-note">Browse inside Forge. Agents inspect and act on the same page, within your permission profile.</p><form className="native-browser-address" onSubmit={event => { event.preventDefault(); void nativeAction(nativeBrowser?.running ? 'browser_native_navigate' : 'browser_native_open', address.trim() ? { url: address.trim() } : {}); }}><input type="url" aria-label="Browser address" placeholder="https://example.com" value={address} onChange={event => setAddress(event.target.value)} /><button className="primary" disabled={!nativeBrowser?.available || busy}>{nativeBrowser?.running ? 'Go' : 'Open browser'}</button></form>{nativeBrowser?.running && <div className="native-browser-controls"><IconButton label="Browser back" onClick={() => void nativeAction('browser_native_back')} disabled={busy || !nativeBrowser.capabilities?.includes('back')}><ArrowLeft size={16} /></IconButton><IconButton label="Browser forward" onClick={() => void nativeAction('browser_native_forward')} disabled={busy || !nativeBrowser.capabilities?.includes('forward')}><ArrowRight size={16} /></IconButton><IconButton label="Reload browser" onClick={() => void nativeAction('browser_native_reload')} disabled={busy}><RotateCw size={15} /></IconButton><span title={nativeBrowser.url}>{nativeBrowser.title || nativeBrowser.url || 'New page'}</span><button className="secondary" disabled={busy} onClick={() => void nativeAction('browser_native_show')}>Show browser</button><IconButton label="Close browser" onClick={() => void nativeAction('browser_native_close')} disabled={busy}><X size={16} /></IconButton></div>}<small className="native-browser-engine">{nativeBrowser?.engine || 'Windows WebView2'} · No additional browser download</small></section>
    <details className="browser-optional" open={!isNative()} onToggle={event => { if (event.currentTarget.open) void refresh(true); }}><summary>Optional isolated browser</summary><section className="settings-card"><div className="runtime-description"><Globe size={22} /><div><strong>Playwright Chromium</strong><p>{isolated.message || 'Checking browser availability…'}</p></div><Badge>{isolated.available ? 'Ready' : 'Setup'}</Badge></div><div className="runtime-controls"><button className="secondary" disabled={!isolated.dependency_available || isolated.installation?.state === 'downloading'} onClick={() => void api('browser_install').then(() => { notify('Chromium installation started.'); void refresh(); }).catch(e => notify(errorText(e)))}><Download size={14} />{isolated.installation?.state === 'downloading' ? 'Installing…' : isolated.available ? 'Verify installation' : 'Install browser'}</button></div>{isolated.installation?.progress?.length ? <details className="runtime-output" open={isolated.installation.state === 'downloading'}><summary>Installation output</summary><pre>{isolated.installation.progress.slice(-12).join('\n')}</pre></details> : null}{isolated.installation?.error && <ErrorNotice error={isolated.installation.error} />}</section></details><details className="browser-optional"><summary>Connect existing Chrome / Edge tabs</summary><section className="settings-card"><div className="runtime-description"><Monitor size={24} /><div><strong>Optional browser extension</strong><p>Connect only the tabs you select in the Forge extension.</p></div></div>{status.connected_tabs?.map((tab, index) => <div className="provider-row" key={tab.id || tab.tab_id || index}><Link size={15} /><div><strong>{tab.title || 'Connected tab'}</strong><small>{tab.url}</small></div><Badge>Connected</Badge></div>)}<button className="card-footer-button" disabled={!isNative()} onClick={() => void api('browser_extension_open_folder').catch(e => setError(errorText(e)))}><Download size={14} />Open extension folder</button><button className="card-footer-button" disabled={!isNative()} onClick={() => { setRegister(true); setError(''); }}><Link size={14} />Connect extension host</button></section></details>{error && <ErrorNotice error={error} />}
    {register && <Modal title="Connect the browser extension" close={() => setRegister(false)}><p className="muted">Load the included browser-extension folder from Chrome or Edge's Extensions page, then copy its extension ID.</p><form onSubmit={e => { e.preventDefault(); setBusy(true); void api('browser_host_register', { extension_id: extensionId, ...(executable.trim() ? { host_executable: executable.trim() } : {}) }).then(() => { notify('Extension host registered. Use the Forge extension to connect a tab.'); setRegister(false); void refresh(); }).catch(e => setError(errorText(e))).finally(() => setBusy(false)); }}><Field label="Extension ID"><input required autoFocus pattern="[a-p]{32}" value={extensionId} onChange={e => setExtensionId(e.target.value.trim())} placeholder="32-character extension ID" /></Field><Field label="Native host path (optional)" hint="Forge finds the bundled Windows host automatically. Set a path only for a custom installation."><input value={executable} onChange={e => setExecutable(e.target.value)} placeholder="Absolute path to forge-browser-host.exe" /></Field>{error && <ErrorNotice error={error} />}<footer><button className="primary" disabled={busy}>{busy ? 'Registering…' : 'Register host'}</button></footer></form></Modal>}
  </>;
}
export function PairBrowserSettings() {
  const [pairing, setPairing] = useState<{ code: string; expires_in: number; url?: string } | null>(null); const [error, setError] = useState('');
  if (!isNative()) return <div className="setting-row"><div><span>Browser session</span><small>This browser is paired with the local coordinator.</small></div><button className="text-button" onClick={() => void api('unpair').then(() => location.reload())}>Unpair</button></div>;
  return <><div className="setting-row"><div><span>Pair a browser</span><small>Use the same workspace in a local browser tab.</small></div><button className="secondary" onClick={() => void api<typeof pairing>('pair_browser').then(setPairing).catch(e => setError(errorText(e)))}>Generate code</button></div>{pairing && <div className="pairing-code"><strong>{pairing.code}</strong><small>Single use · Expires in {Math.round(pairing.expires_in / 60)} minutes</small>{pairing.url && <a href={pairing.url} target="_blank" rel="noopener noreferrer">Open local workspace</a>}</div>}{error && <ErrorNotice error={error} />}</>;
}
