import { useEffect, useState } from 'react';
import { api, errorText } from './api';
import { Badge, Toggle } from './components';
import type { Settings } from './types';
interface Calibration {id:string;model:string;context:number;validated:boolean;median_total_seconds:number;quality_scope:string;}
export function CalibrationSettings({settings,onChange,notify}:{settings:Settings;onChange:(delta:Partial<Settings>)=>Promise<void>;notify:(text:string)=>void}) {
  const [profiles,setProfiles]=useState<Calibration[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
  async function refresh(){try{const result=await api<{calibrations:Calibration[]}>('performance_calibrations');setProfiles(result.calibrations || []);}catch(e){setError(errorText(e));}}
  useEffect(()=>{void refresh();},[settings.model,settings.context]);
  async function calibrate(){setBusy(true);try{await api('performance_calibrate',{provider_id:settings.provider_id || 'ollama',model:settings.model,context:settings.context,tools:true,vision:true});notify('Repeated calibration queued. Keep chats paused until it finishes. Refresh profiles after completion.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function approve(id:string){try{const result=await api<{settings:Settings}>('performance_profile_accept',{id});await onChange({adaptive_profile_ids:result.settings.adaptive_profile_ids});notify('Calibration approved for opt-in adaptive use.');}catch(e){setError(errorText(e));}}
  const approved=Array.isArray(settings.adaptive_profile_ids)?settings.adaptive_profile_ids as string[]:[];
  return <><h2>Measured adaptive profiles</h2><section className="settings-card"><p>Calibration measures five warm coding repetitions, longer prompts, and supported tool/image probes. It does not establish complete app-building quality.</p>{error && <p role="alert">{error}</p>}<Toggle label="Adaptive local tuning" description="Use only approved calibrations. Explicit model and context locks stay authoritative." checked={Boolean(settings.adaptive_enabled)} onChange={value=>void onChange({adaptive_enabled:value})}/><Toggle label="Lock selected model" checked={settings.adaptive_model_locked !== false} onChange={value=>void onChange({adaptive_model_locked:value})}/><Toggle label="Lock selected context" checked={settings.adaptive_context_locked !== false} onChange={value=>void onChange({adaptive_context_locked:value})}/><div className="benchmark-options"><button className="secondary" disabled={busy || !settings.model} onClick={()=>void calibrate()}>Run repeated calibration</button><button className="subtle" onClick={()=>void refresh()}>Refresh profiles</button></div>{profiles.map(profile=><div className="recommendation" key={profile.id}><div><strong>{profile.model}</strong><p>{profile.context/1024}K · {profile.median_total_seconds.toFixed(2)} s median probe</p><small>{profile.quality_scope}</small></div><Badge>{approved.includes(profile.id)?'Approved':profile.validated?'Passed':'Failed'}</Badge>{profile.validated && !approved.includes(profile.id) && <button className="secondary" onClick={()=>void approve(profile.id)}>Approve profile</button>}</div>)}</section></>;
}
