import { useEffect, useState } from 'react';
import { api, tokenLabel } from './api';
import type { Settings } from './types';
const presets = [{ name: 'Low', tokens: 2048 }, { name: 'Medium', tokens: 8192 }, { name: 'High', tokens: 32768 }, { name: 'Max', tokens: 131072 }, { name: 'Ultra', tokens: 262144 }];
export function ContextSettings({ settings, onChange }: { settings: Settings; onChange: (delta: Partial<Settings>) => Promise<void> }) {
  const [limit, setLimit] = useState<number | null>(null);
  useEffect(() => { let disposed = false; setLimit(null); if (settings.model) void api<{ model_info?: Record<string, unknown>; context_limit?: number; context_length?: number; max_context?: number }>('show', { model: settings.model, provider_id: settings.provider_id || 'ollama' }).then(result => { const value = result.context_limit || result.context_length || result.max_context || Object.entries(result.model_info || {}).find(([key]) => key.endsWith('.context_length'))?.[1]; if (!disposed) setLimit(typeof value === 'number' ? value : null); }).catch(() => {}); return () => { disposed = true; }; }, [settings.model, settings.provider_id]);
  return <div className="context-setting"><label htmlFor="context-window">Context window<output>{tokenLabel(settings.context)}</output></label><div className="context-presets" role="group" aria-label="Context presets">{presets.map(preset => <button type="button" className={preset.tokens === settings.context ? 'selected' : ''} aria-pressed={preset.tokens === settings.context} aria-label={`${preset.name} ${tokenLabel(preset.tokens)}`} title={preset.name === 'Ultra' ? 'Highest available setting: 256K context. Your model must support this capacity.' : `${tokenLabel(preset.tokens)} context`} key={preset.name} onClick={() => void onChange({ context: preset.tokens })}><span>{preset.name}</span><strong>{tokenLabel(preset.tokens)}</strong></button>)}</div><input id="context-window" type="range" min="2048" max="262144" step="2048" value={settings.context} aria-valuetext={`${tokenLabel(settings.context)} tokens`} onChange={event => void onChange({ context: Number(event.target.value) })} /><div className="range-labels"><span>2K</span><span>128K</span><span>256K</span></div><small>{limit ? `Selected model reports up to ${tokenLabel(limit)} context.` : 'Model context capacity has not been reported.'} Larger windows use more memory.</small>{limit && settings.context > limit ? <p className="context-capability-warning" role="status">This selection exceeds the model’s reported {tokenLabel(limit)} limit. Choose a supported window before prompting.</p> : null}</div>;
}
