import { useEffect, useState } from 'react';
import { Download, Mic, RefreshCw } from 'lucide-react';
import { api, errorText } from './api';
import { Badge, ErrorNotice, IconButton } from './components';
import type { Settings } from './types';
interface DictationStatus { state?: string; model?: string; model_installed?: boolean; setup_required?: boolean; message?: string; error?: string; device?: string; compute_type?: string; }
export function DictationSettings({ settings, onChange, notify }: { settings: Settings; onChange: (delta: Partial<Settings>) => Promise<void>; notify: (message: string) => void }) {
  const [status, setStatus] = useState<DictationStatus>({}); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function refresh() { try { const result = await api<DictationStatus>('dictation_status'); setStatus(result); setError(''); } catch (e) { setError(errorText(e)); } }
  useEffect(() => { void refresh(); }, []);
  useEffect(() => { if (status.state !== 'installing') return; const timer = setInterval(() => void refresh(), 1200); return () => clearInterval(timer); }, [status.state]);
  const ready = status.model_installed && !status.setup_required && (!status.model || status.model === (settings.dictation_model || 'base'));
  async function install() { setBusy(true); setError(''); try { const result = await api<DictationStatus>('dictation_install', { model: settings.dictation_model || 'base' }); setStatus(result); notify(result.state === 'ready' ? 'Dictation model is ready.' : result.message || 'Dictation model preparation started.'); } catch (e) { setError(errorText(e)); notify(errorText(e)); } finally { setBusy(false); } }
  return <><div className="settings-section-heading"><h2>Local dictation</h2><IconButton label="Refresh dictation status" onClick={() => void refresh()}><RefreshCw size={15} /></IconButton></div><section className="settings-card"><div className="runtime-description"><Mic size={24} /><div><strong>Push-to-talk</strong><p>{status.message || 'Record locally, then edit the transcript before sending.'}</p></div><Badge>{status.state === 'installing' ? 'Installing…' : ready ? 'Ready' : error || status.state === 'error' ? 'Needs attention' : 'Setup'}</Badge></div><div className="setting-row"><span>Speech model</span><select aria-label="Dictation model" disabled={busy || status.state === 'installing'} value={String(settings.dictation_model || 'base')} onChange={event => { setError(''); void onChange({ dictation_model: event.target.value }).then(() => refresh()); }}><option value="tiny">Tiny multilingual</option><option value="base">Base multilingual</option><option value="small">Small multilingual</option></select></div><div className="setting-row"><span>Compute</span><Badge>{(status.device || 'cpu').toUpperCase()} · {(status.compute_type || 'int8').toUpperCase()}</Badge></div><button className="card-footer-button" disabled={busy || status.state === 'installing'} onClick={() => void install()}><Download size={14} />{busy || status.state === 'installing' ? 'Preparing model…' : ready ? 'Verify installed model' : 'Prepare dictation model'}</button></section><p className="page-footnote">Uses your Windows default microphone. Click the microphone in the composer to start and stop recording. Audio stays in memory and is discarded after transcription or cancellation.</p>{(error || status.error) && <ErrorNotice error={error || status.error || ''} retry={() => void refresh()} />}</>;
}
