import { useEffect, useState } from 'react';
import { api, errorText } from './api';
import { Badge, ErrorNotice, Field, Modal } from './components';
import type { Goal } from './types';

export function GoalTaskEvidence({goal,conflict,onAccepted}: {goal:Goal;conflict:boolean;onAccepted:(goal:Goal)=>void}) {
  const [accept,setAccept]=useState<{id:string;run_id:string;task_id:string;expected_revision:number;text:string}|null>(null);
  const [note,setNote]=useState(''),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [notice,setNotice]=useState('');useEffect(()=>setNotice(''),[goal.id]);
  const verified=new Set(goal.progress_summary?.verified_task_ids || []);
  async function submit(){if(!accept||!reviewed||!note.trim())return;setBusy(true);setError('');try{const result=await api<{goal:Goal}>('goal_task_accept',{id:accept.id,run_id:accept.run_id,task_id:accept.task_id,expected_revision:accept.expected_revision,note:note.trim(),evidence_ids:[]});onAccepted(result.goal);setNotice('Human review recorded');setAccept(null);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  return <div className="goal-task-evidence">{notice && <p role="status">{notice}</p>}{goal.tasks?.map(task=><details key={task.id}><summary>{task.text || task.title || 'Task'} <Badge>{verified.has(task.id)?'Verified':goal.execution_mode==='guided'?'Needs verification':task.status}</Badge></summary><p className="muted">{task.evidence?.length?'Recorded evidence:':'No evidence references recorded.'}</p>{task.evidence?.map((evidence,index)=><pre key={index}>{typeof evidence==='string'?evidence:JSON.stringify(evidence,null,2)}</pre>)}{goal.execution_mode==='guided'&&!verified.has(task.id)&&goal.run_id&&Number.isInteger(goal.revision)&&<><p className="muted">For checks this workflow cannot verify, review the current result yourself and record what you observed.</p><button className="secondary" disabled={conflict||!['paused','interrupted','failed','ready'].includes(goal.status)} onClick={()=>{setAccept({id:goal.id,run_id:goal.run_id!,task_id:task.id,expected_revision:goal.revision!,text:task.text || task.title || 'Task'});setNote('');setReviewed(false);setError('');}}>Accept checked task</button></>}</details>)}{accept && <Modal title="Accept checked task" close={()=>{if(!busy)setAccept(null);}}><p><strong>{accept.text}</strong></p><p className="muted">This records your review of this task's current outcome. The coordinator also requires the goal's other checks and independent review.</p><Field label="What did you check?"><textarea autoFocus maxLength={2000} rows={4} value={note} onChange={event=>setNote(event.target.value)} placeholder="Describe the current result you inspected and what confirms the acceptance criteria."/></Field><label className="checkbox-row"><input type="checkbox" checked={reviewed} onChange={event=>setReviewed(event.target.checked)}/>I reviewed this task's current result</label>{error && <ErrorNotice error={error}/>}<footer><button className="secondary" disabled={busy} onClick={()=>setAccept(null)}>Cancel</button><button className="primary" disabled={busy||!reviewed||!note.trim()} onClick={()=>void submit()}>Record acceptance</button></footer></Modal>}</div>;
}
