import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Download, FileBox, KeyRound, RefreshCw, Search, Square } from 'lucide-react';
import { api, bytesLabel, errorText } from './api';
import { Badge, Empty, ErrorNotice, Field, IconButton, Modal } from './components';

interface HubModel { repo_id: string; downloads?: number; likes?: number; license?: string; gated?: boolean; vision?: boolean; tags?: string[]; }
interface HubFile { path: string; size?: number | null; quantization?: string; is_projector: boolean; downloadable?: boolean; sha256?: string; local_path?: string; }
interface HubInspection { repo_id: string; revision: string; license?: string; gated?: boolean; vision?: boolean; files: HubFile[]; warnings?: string[]; }
interface HubStatus { dependency_available?: boolean; authenticated?: boolean; download_root?: string; message?: string; }
interface HubJob { id: string; kind: 'download' | 'import'; status: string; repo_id: string; revision: string; filenames?: string[]; files: HubFile[]; license?: string; total_bytes?: number; completed_bytes?: number; current_file?: string; message?: string; error?: string; model_name?: string; capabilities?: string[]; warnings?: string[]; vision?: boolean; }
interface OllamaTarget { id: string; name: string; kind?: string; type?: string; }
const active = new Set(['queued', 'downloading', 'verifying', 'importing', 'cancelling']);
function modelGroup(file: HubFile, files: HubFile[]) { const match = file.path.match(/^(.*)-\d{5}-of-(\d{5})\.gguf$/i); return match ? files.filter(item => item.path.startsWith(match[1] + '-') && item.path.endsWith(`-of-${match[2]}.gguf`)) : [file]; }
export function HuggingFaceModels({ notify, refreshModels }: { notify: (text: string) => void; refreshModels: () => Promise<void> }) {
  const [status, setStatus] = useState<HubStatus>({}); const [models, setModels] = useState<HubModel[]>([]); const [jobs, setJobs] = useState<HubJob[]>([]); const [targets, setTargets] = useState<OllamaTarget[]>([]);
  const [query, setQuery] = useState(''); const [searched, setSearched] = useState(false); const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const [inspection, setInspection] = useState<HubInspection | null>(null); const [selected, setSelected] = useState<string[]>([]); const [fileSearch, setFileSearch] = useState('');
  const [auth, setAuth] = useState(false); const [token, setToken] = useState(''); const [importJob, setImportJob] = useState<HubJob | null>(null); const [filename, setFilename] = useState(''); const [projector, setProjector] = useState(''); const [textOnly, setTextOnly] = useState(false); const [name, setName] = useState(''); const [providerId, setProviderId] = useState('ollama');
  const refreshedImports = useRef(new Set<string>()); const polling = useRef(false);
  async function refresh() { if (polling.current) return; polling.current = true; try { const result = await api<{ jobs: HubJob[] }>('hf_jobs'); setJobs(result.jobs || []); for (const job of result.jobs || []) if (job.kind === 'import' && job.status === 'completed' && !refreshedImports.current.has(job.id)) { refreshedImports.current.add(job.id); await refreshModels(); } } catch (e) { setError(errorText(e)); } finally { polling.current = false; } }
  useEffect(() => { void api<HubStatus>('hf_status').then(setStatus).catch(e => setError(errorText(e))); void api<{ providers: OllamaTarget[] }>('providers').then(result => setTargets(result.providers.filter(item => item.kind === 'ollama' || item.type === 'ollama'))).catch(() => {}); void refresh(); }, []);
  const running = jobs.some(job => active.has(job.status));
  useEffect(() => { if (!running) return; const timer = setInterval(() => void refresh(), 1000); return () => clearInterval(timer); }, [running]);
  async function search() { setBusy('search'); setError(''); try { const result = await api<{ models: HubModel[] }>('hf_search', { query: query.trim(), limit: 20 }); setModels(result.models || []); setSearched(true); } catch (e) { setError(errorText(e)); } finally { setBusy(''); } }
  async function inspect(repo: string) { setBusy('inspect'); setError(''); try { const result = await api<HubInspection>('hf_files', { repo_id: repo }); setInspection(result); setSelected([]); setFileSearch(''); } catch (e) { setError(errorText(e)); } finally { setBusy(''); } }
  function choose(file: HubFile, checked: boolean) { if (!inspection) return; const group = file.is_projector ? [file] : modelGroup(file, inspection.files); setSelected(prev => checked ? [...new Set([...prev, ...group.map(item => item.path)])] : prev.filter(path => !group.some(item => item.path === path))); }
  async function download() { if (!inspection) return; setBusy('download'); setError(''); try { const result = await api<{ job: HubJob }>('hf_download', { repo_id: inspection.repo_id, revision: inspection.revision, filenames: selected }); setJobs(prev => [result.job, ...prev]); setInspection(null); notify('GGUF download started. Import becomes available after verification.'); await refresh(); } catch (e) { setError(errorText(e)); } finally { setBusy(''); } }
  async function authenticate(clear = false) { setBusy('auth'); setError(''); try { setStatus(await api<HubStatus>('hf_auth', { token: clear ? '' : token.trim() })); setToken(''); setAuth(false); notify(clear ? 'Hugging Face read token removed.' : 'Hugging Face read token saved in the credential vault.'); } catch (e) { setError(errorText(e)); } finally { setBusy(''); } }
  function openImport(job: HubJob) { const model = job.files.find(file => !file.is_projector); setImportJob(job); setFilename(model?.path || ''); setProjector(''); setTextOnly(false); const base = job.repo_id.split('/').at(-1)?.replace(/-gguf$/i, '').replace(/[^a-zA-Z0-9_.-]/g, '-') || 'forge-model'; setName(`${base}:${(model?.quantization || 'local').toLowerCase()}`); setError(''); }
  async function importModel() { if (!importJob) return; setBusy('import'); setError(''); try { const result = await api<{ job: HubJob }>('hf_import', { job_id: importJob.id, filename, model_name: name.trim(), provider_id: providerId, projector: projector || undefined, text_only: textOnly }); setJobs(prev => [result.job, ...prev]); setImportJob(null); notify('Ollama import started. The model appears after the engine verifies it.'); await refresh(); } catch (e) { setError(errorText(e)); } finally { setBusy(''); } }
  async function jobAction(action: string, id: string) { setBusy(id); setError(''); try { await api(action, { id }); await refresh(); } catch (e) { setError(errorText(e)); } finally { setBusy(''); } }
  const selectedBytes = inspection?.files.filter(file => selected.includes(file.path)).reduce((sum, file) => sum + (file.size || 0), 0) || 0;
  const repoFiles = inspection?.files.filter(file => file.downloadable !== false && file.path.toLowerCase().endsWith('.gguf') && (!fileSearch || file.path.toLowerCase().includes(fileSearch.toLowerCase()))) || [];
  return <div className="hub-models"><div className="settings-section-heading"><h2>Hugging Face models</h2><div className="hub-auth-actions"><Badge>{status.authenticated ? 'Read token saved' : 'Public access'}</Badge><button className="text-button" onClick={() => { setAuth(true); setToken(''); setError(''); }}><KeyRound size={13} />{status.authenticated ? 'Manage token' : 'Add read token'}</button></div></div><p className="page-footnote">Find GGUF weights, choose a quantization and matching vision projector, then import into Ollama. Public models do not need an account.</p>
    {error && !inspection && !auth && !importJob && <ErrorNotice error={error} />}
    <form className="hub-search" onSubmit={event => { event.preventDefault(); void search(); }}><div className="search-input"><Search size={16} /><input aria-label="Search Hugging Face models" placeholder="Model name or owner/repository" value={query} onChange={event => setQuery(event.target.value)} required /></div><button className="secondary" disabled={Boolean(busy) || !status.dependency_available}>{busy === 'search' ? 'Searching…' : 'Search'}</button>{query.includes('/') && <button type="button" className="text-button" disabled={Boolean(busy)} onClick={() => void inspect(query.trim())}>Inspect repository</button>}</form>
    {status.dependency_available === false && <ErrorNotice error="Hugging Face support is unavailable in this build. Install the integrations dependencies or use a complete Forge package." />}
    <section className="hub-results">{models.map(model => <article className="hub-model-result" key={model.repo_id}><FileBox size={19} /><div><strong>{model.repo_id}</strong><div className="hub-tags"><Badge>{model.license || 'License not reported'}</Badge>{model.gated && <Badge>Gated</Badge>}{model.vision && <Badge>Vision repository</Badge>}<span>{(model.downloads || 0).toLocaleString()} downloads</span></div></div><button className="secondary" disabled={Boolean(busy)} onClick={() => void inspect(model.repo_id)}>Choose files</button><a className="hub-repo-link" href={`https://huggingface.co/${model.repo_id}`} target="_blank" rel="noopener noreferrer" aria-label={`View ${model.repo_id} on Hugging Face`}><ArrowUpRight size={15} /></a></article>)}{searched && !models.length && !busy && <Empty icon={<Search size={24} />} title="No matching models" text="Try another model name or inspect an exact owner/repository." />}</section>
    <div className="settings-section-heading"><h2>Downloads & imports</h2><IconButton label="Refresh model downloads" onClick={() => void refresh()}><RefreshCw size={15} /></IconButton></div><section className="settings-card hub-jobs">{jobs.length ? jobs.slice(0, 12).map(job => { const progress = job.total_bytes ? Math.min(100, (job.completed_bytes || 0) / job.total_bytes * 100) : 0; return <article className="hub-job" key={job.id}><header><div><strong>{job.model_name || job.repo_id}</strong><small>{job.kind === 'import' ? 'Ollama import' : 'GGUF download'} · {job.revision.slice(0, 10)}</small></div><Badge tone={job.status === 'completed' ? 'accent' : ''}>{job.status.replaceAll('_', ' ')}</Badge>{active.has(job.status) && <IconButton label={`Cancel ${job.kind}`} disabled={job.status === 'cancelling' || busy === job.id} onClick={() => void jobAction('hf_cancel', job.id)}><Square size={13} /></IconButton>}</header>{active.has(job.status) && <><progress value={job.completed_bytes || 0} max={job.total_bytes || 1} aria-label={`${job.kind} file transfer`} /><div className="hub-progress-label"><span>{bytesLabel(job.completed_bytes || 0) || '0 B'} / {bytesLabel(job.total_bytes || 0) || '0 B'}</span><span>{progress.toFixed(0)}% transferred</span></div></>}<p>{job.message || job.current_file || (job.status === 'completed' ? 'Complete.' : 'Waiting…')}</p>{job.error && <ErrorNotice error={job.error} />}{job.warnings?.map((warning, index) => <p className="page-footnote" key={index}>{warning}</p>)}{job.capabilities?.length ? <div className="hub-tags">{job.capabilities.map(capability => <Badge key={capability}>{capability}</Badge>)}</div> : null}<footer>{job.kind === 'download' && job.status === 'completed' && <button className="secondary" onClick={() => openImport(job)}>Import into Ollama</button>}{['failed', 'cancelled', 'interrupted'].includes(job.status) && <button className="secondary" disabled={Boolean(busy)} onClick={() => void jobAction('hf_retry', job.id)}>Retry</button>}{job.status === 'import_unknown' && <button className="secondary" disabled={Boolean(busy)} onClick={() => void jobAction('hf_reconcile', job.id)}>Check import outcome</button>}<small>{job.license || 'License not reported'}</small></footer></article>; }) : <div className="card-note">Selected downloads and imports appear here. Model files remain on your computer.</div>}</section>
    {inspection && <Modal title="Choose model files" wide close={() => { if (!busy) setInspection(null); }}><div className="hub-inspection-heading"><strong>{inspection.repo_id}</strong><a href={`https://huggingface.co/${inspection.repo_id}`} target="_blank" rel="noopener noreferrer">Review model card <ArrowUpRight size={13} /></a></div><div className="hub-tags"><Badge>{inspection.license || 'License not reported'}</Badge><Badge>Revision {inspection.revision.slice(0, 10)}</Badge>{inspection.gated && <Badge>Gated model</Badge>}</div><p className="muted">Choose a compatible quantization and review the repository license. Split model shards are selected together.</p>{inspection.warnings?.map((warning, index) => <p className="hub-warning" key={index}>{warning}</p>)}<div className="search-input"><Search size={15} /><input aria-label="Filter model files" placeholder="Filter by filename or quantization" value={fileSearch} onChange={event => setFileSearch(event.target.value)} /></div><div className="hub-file-list">{repoFiles.slice(0, 200).map(file => <label className="hub-file" key={file.path}><input type="checkbox" checked={selected.includes(file.path)} disabled={file.size === null || file.size === undefined || Boolean(busy)} onChange={event => choose(file, event.target.checked)} /><div><strong>{file.path}</strong><small>{file.is_projector ? 'Vision projector' : file.quantization || 'GGUF weights'}</small></div><span>{typeof file.size === 'number' ? bytesLabel(file.size) : 'Size unavailable'}</span></label>)}{!repoFiles.length && <p className="muted">No compatible GGUF files are listed.</p>}{repoFiles.length > 200 && <p className="muted">Showing 200 files. Filter to find the remaining files.</p>}</div>{error && <ErrorNotice error={error} />}<footer><span className="hub-selection-total">{selected.length} files · {bytesLabel(selectedBytes) || '0 B'}</span><button className="subtle" disabled={Boolean(busy)} onClick={() => setInspection(null)}>Cancel</button><button className="primary" disabled={!selected.length || selected.length > 128 || Boolean(busy)} onClick={() => void download()}><Download size={14} />{busy === 'download' ? 'Starting…' : 'Download selected files'}</button></footer></Modal>}
    {auth && <Modal title="Hugging Face read token" close={() => { setAuth(false); setToken(''); }}><p className="muted">Optional for gated repositories. Accept the model’s access terms on Hugging Face first. Forge stores the token in the operating system credential vault.</p><form onSubmit={event => { event.preventDefault(); void authenticate(); }}><Field label="Read token"><input autoFocus type="password" autoComplete="off" value={token} onChange={event => setToken(event.target.value)} placeholder="hf_…" /></Field>{error && <ErrorNotice error={error} />}<footer>{status.authenticated && <button type="button" className="text-button" disabled={Boolean(busy)} onClick={() => void authenticate(true)}>Remove saved token</button>}<button className="primary" disabled={!token.trim() || Boolean(busy)}>Save token</button></footer></form></Modal>}
    {importJob && <Modal title="Import into Ollama" wide close={() => { if (!busy) setImportJob(null); }}><p className="muted">Choose an unused model name. Forge verifies the downloaded GGUF files and discovers capabilities after the engine creates the model.</p><Field label="Model weights"><select value={filename} onChange={event => setFilename(event.target.value)}>{importJob.files.filter(file => !file.is_projector).map(file => <option key={file.path} value={file.path}>{file.path}</option>)}</select></Field><Field label="Vision projector" hint="Choose the matching projector to retain vision."><select value={projector} onChange={event => setProjector(event.target.value)}><option value="">No projector selected</option>{importJob.files.filter(file => file.is_projector).map(file => <option key={file.path} value={file.path}>{file.path}</option>)}</select></Field>{importJob.vision && !projector && <label className="checkbox-control"><input type="checkbox" checked={textOnly} onChange={event => setTextOnly(event.target.checked)} />Import without vision (text-only)</label>}<div className="form-grid"><Field label="Ollama model name"><input value={name} onChange={event => setName(event.target.value)} placeholder="forge-model:q4_k_m" required /></Field><Field label="Ollama engine"><select value={providerId} onChange={event => setProviderId(event.target.value)}><option value="ollama">Ollama</option>{targets.filter(target => target.id !== 'ollama').map(target => <option value={target.id} key={target.id}>{target.name}</option>)}</select></Field></div><p className="page-footnote">License: {importJob.license || 'not reported'}. Downloaded files can also be selected in a managed llama.cpp runtime.</p>{error && <ErrorNotice error={error} />}<footer><button className="subtle" disabled={Boolean(busy)} onClick={() => setImportJob(null)}>Cancel</button><button className="primary" disabled={!name.trim() || !filename || Boolean(busy) || Boolean(importJob.vision && !projector && !textOnly)} onClick={() => void importModel()}>{busy === 'import' ? 'Starting…' : 'Import model'}</button></footer></Modal>}
  </div>;
}
