import { useEffect, useState } from 'react';
import { Bot, Check, KeyRound } from 'lucide-react';
import { api, errorText } from './api';
import { Badge, ErrorNotice, Field, Toggle } from './components';
import type { Agent, Settings } from './types';
interface Provider { enabled?: boolean; connected?: boolean; remote_consent?: boolean; data_collection?: string; account?: { free_model_daily_requests?: { used: number; limit: number; remaining: number }; quota_note?: string }; models?: { name: string }[]; }
export function OpenRouterSettings({ notify, settings, onChange }: { notify: (v: string) => void; settings?: Settings; onChange?: (v: Partial<Settings>) => Promise<void> }) {
  const [provider, setProvider] = useState<Provider>({}); const [key, setKey] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  useEffect(() => { void api<{ provider: Provider }>('openrouter_status').then(r => setProvider(r.provider || {})).catch(e => setError(errorText(e))); }, []);
  async function save(test = false) { setBusy(true); setError(''); try { const saved = await api<{ provider: Provider }>('openrouter_save', { ...provider, ...(key ? { api_key: key } : {}) }); setKey(''); setProvider(saved.provider); if (test) { const checked = await api<{ provider: Provider }>('openrouter_test'); setProvider(checked.provider); } } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function createResearcher() { try { const agents = await api<{ agents: Agent[] }>('agents'); const existing = agents.agents.find(a => a.provider_id === 'openrouter' && a.name === 'Free research'); await api('agent_save', { id: existing?.id, name: 'Free research', role: 'researcher', provider_id: 'openrouter', model: 'openrouter/free', context: 8192, enabled: true, instructions: 'Research the assigned question using primary sources. Cite URLs and report uncertainty. Keep the response concise for the main agent. Do not edit files, run commands or delegate recursively.', tools: ['web_search','web_fetch','read_file','search_files','artifact_read'], skills: [], tokens: 8000, rounds: 12 }); notify('Free research profile is ready in Agents. Enable automatic delegation when you want the main model to assign tasks.'); } catch (e) { setError(errorText(e)); } }
  const quota = provider.account?.free_model_daily_requests;
  return <><h2>OpenRouter free sub-agents</h2><section className="settings-card"><div className="setting-row"><div><strong>Free models router</strong><small>Remote research without loading another model into local VRAM.</small></div><Badge>{provider.connected ? 'Connected' : 'Setup needed'}</Badge></div><Field label="OpenRouter API key" hint="Stored in Windows Credential Manager. Leave blank to keep the saved key."><input type="password" autoComplete="off" value={key} onChange={e => setKey(e.target.value)} placeholder="Paste your key here, never in chat" /></Field><Toggle label="Allow assigned context to leave this computer" description="OpenRouter and its model provider receive the selected agent’s prompt and tool results. Local-only chat stays available." checked={Boolean(provider.remote_consent)} onChange={remote_consent => setProvider({ ...provider, remote_consent })} /><Toggle label="Enable free OpenRouter agents" checked={Boolean(provider.enabled)} onChange={enabled => setProvider({ ...provider, enabled })} /><Toggle label="Allow providers that collect data" description="Off requests providers that do not collect prompt data. Free providers may be unavailable under this restriction." checked={provider.data_collection === 'allow'} onChange={allow => setProvider({ ...provider, data_collection: allow ? 'allow' : 'deny' })} />{settings && onChange && <Toggle label="Automatic delegation" description="Let the main agent assign bounded tasks to enabled agent profiles. Each profile keeps its own model and tool scope." checked={Boolean(settings.auto_delegate)} onChange={auto_delegate => void onChange({ auto_delegate })} />}{error && <ErrorNotice error={error} />}<div className="setup-actions"><button className="primary" disabled={busy} onClick={() => void save()}><KeyRound size={14} />Save connection</button><button className="secondary" disabled={busy} onClick={() => void save(true)}><Check size={14} />Connect / Test</button><button className="secondary" disabled={!provider.enabled || !provider.connected} onClick={() => void createResearcher()}><Bot size={14} />Create research profile</button></div>{quota && <p className="muted">Free requests today: {quota.used} / {quota.limit} · {quota.remaining} remaining.</p>}<p className="muted">Forge restricts this connection to advertised free models and zero-price routes. It never switches to a paid model. OpenRouter availability and request limits still apply.</p><a href="https://openrouter.ai/settings/keys" target="_blank" rel="noopener noreferrer">Create an OpenRouter key</a></section></>;
}
