import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowUpRight, BookOpen, Bug, Check, ChevronRight, ClipboardList, Code2, Compass, FileText, FlaskConical, GitPullRequest, Globe, Layers3, LoaderCircle, Package, Plug, Plus, RefreshCw, Search, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { api, errorText } from './api';
import { Badge, Empty, ErrorNotice, Field, IconButton, Markdown, Modal, PageHeader, useResource } from './components';
import type { Plugin } from './types';
import { SkillWorkbench } from './skillWorkbench';
import './library.css';

export interface LibrarySkill { id: string; name: string; description?: string; path?: string; scope?: string; enabled: boolean; automatic: boolean; category?: string; bundle?: string; tags?: string[]; source?: string; license?: string; builtin?: boolean; library_id?: string; plugin_id?: string; }
export interface LibraryEntry { id: string; name: string; description?: string; kind: string; category?: string; bundle?: string; source?: string; source_id?: string; source_name?: string; catalog_name?: string; license?: string; compatibility?: string; version?: string; installed?: boolean; enabled?: boolean; automatic?: boolean; skill_id?: string; plugin_id?: string; tags?: string[]; builtin?: boolean; reviewed?: boolean; setup?: string | string[]; featured?: boolean; }
interface LibrarySource { id: string; name: string; source?: string; state?: string; status?: string; count?: number; reviewed?: boolean; builtin?: boolean; error?: string; }
interface LibraryDiscovery { entries: LibraryEntry[]; sources: LibrarySource[]; errors?: { source?: string; name?: string; error?: string }[]; refreshing?: boolean; }
interface Inspection { inspection_id?: string; name: string; description?: string; version?: string; format?: string; compatibility?: string; warnings?: string[]; licenses?: string[]; compatible: boolean; features?: Record<string, unknown>; }
type LibraryKind = 'all' | 'skill' | 'plugin';

function categoryLabel(value = '') { return value.replaceAll(/[_-]/g, ' ').replace(/^\w/, c => c.toUpperCase()); }
function kindLabel(kind: string) { return kind === 'skill' ? 'Skill' : kind === 'mcp' ? 'MCP plugin' : 'Plugin'; }
function SkillIcon({ category = '', kind, size = 22 }: { category?: string; kind?: string; size?: number }) {
  const icons = { research: Globe, coding: Code2, development: Code2, debugging: Bug, testing: FlaskConical, documentation: FileText, writing: FileText, planning: ClipboardList, review: GitPullRequest, workflow: Layers3, productivity: Layers3 };
  const Icon = icons[category.toLowerCase() as keyof typeof icons] || (kind === 'skill' ? BookOpen : Plug);
  return <Icon size={size} strokeWidth={1.65} />;
}
export function filterLibraryEntries(entries: LibraryEntry[], query: string, kind: LibraryKind, category: string, bundle = '') {
  const terms = query.toLocaleLowerCase().trim().split(/\s+/).filter(Boolean);
  return entries.filter(entry => {
    const text = [entry.name, entry.description, entry.category, entry.bundle, entry.catalog_name, entry.source_name, entry.compatibility, entry.license, ...(entry.tags || [])].filter(Boolean).join(' ').toLocaleLowerCase();
    return (kind === 'all' || (kind === 'skill' ? entry.kind === 'skill' : entry.kind !== 'skill')) && (!category || entry.category?.toLocaleLowerCase() === category.toLocaleLowerCase()) && (!bundle || entry.bundle === bundle) && terms.every(term => text.includes(term));
  });
}
function LibrarySwitch({ name, label, value, disabled, change }: { name: string; label: string; value: boolean; disabled?: boolean; change: (value: boolean) => void }) {
  return <div className="library-switch"><span>{label}</span><button className="toggle" type="button" role="switch" aria-label={name} aria-checked={value} disabled={disabled} onClick={() => change(!value)}><span /></button></div>;
}

export function PluginsPage({ notify, projectId }: { notify: (message: string) => void; projectId?: string | null }) {
  const installed = useResource<Plugin>('plugins', 'plugins');
  const skills = useResource<LibrarySkill>('skills', 'skills', { project_id: projectId || undefined });
  const [library, setLibrary] = useState<LibraryDiscovery>({ entries: [], sources: [] });
  const [loading, setLoading] = useState(true); const [discoveryError, setDiscoveryError] = useState(''); const generation = useRef(0); const catalogTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const [tab, setTab] = useState<'discover' | 'installed'>('discover'); const [query, setQuery] = useState(''); const [kind, setKind] = useState<LibraryKind>('all'); const [category, setCategory] = useState(''); const [pending, setPending] = useState<string[]>([]);
  const [importing, setImporting] = useState(false); const [source, setSource] = useState(''); const [inspection, setInspection] = useState<Inspection | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const [sourcesOpen, setSourcesOpen] = useState(false); const [catalogName, setCatalogName] = useState(''); const [catalogSource, setCatalogSource] = useState(''); const [catalogBusy, setCatalogBusy] = useState(false); const [catalogError, setCatalogError] = useState('');
  const [skillSource, setSkillSource] = useState(''); const [addingSkill, setAddingSkill] = useState(false); const [skillImportBusy, setSkillImportBusy] = useState(false); const [skillImportError, setSkillImportError] = useState('');
  const [detail, setDetail] = useState<LibraryEntry | null>(null); const [preview, setPreview] = useState(''); const [previewBusy, setPreviewBusy] = useState(false); const [previewError, setPreviewError] = useState(''); const previewGeneration = useRef(0);
  const [workbench, setWorkbench] = useState<string | null>(null); const [bundle, setBundle] = useState('');

  async function discover(refresh = false, poll = 0) {
    if (catalogTimer.current) clearTimeout(catalogTimer.current);
    const request = ++generation.current; setLoading(true); setDiscoveryError('');
    try { const result = await api<LibraryDiscovery>('catalog_discover', { project_id: projectId || undefined, ...(refresh ? { refresh: true } : {}) }); if (request === generation.current) { setLibrary({ entries: result.entries || [], sources: result.sources || [], errors: result.errors || [], refreshing: result.refreshing }); if (result.refreshing && poll < 20) catalogTimer.current = setTimeout(() => void discover(false, poll + 1), 1500); } }
    catch (e) { if (request === generation.current) setDiscoveryError(errorText(e)); }
    finally { if (request === generation.current) setLoading(false); }
  }
  useEffect(() => { void discover(); return () => { generation.current++; if (catalogTimer.current) clearTimeout(catalogTimer.current); }; }, [projectId]);
  useEffect(() => () => { previewGeneration.current++; }, []);

  const discovered = useMemo(() => library.entries.map(entry => {
    const skill = skills.items.find(item => item.id === entry.skill_id || (item.library_id && item.library_id === entry.id));
    const plugin = installed.items.find(item => item.id === entry.plugin_id);
    return skill ? { ...entry, installed: true, enabled: skill.enabled, automatic: skill.automatic, skill_id: skill.id } : plugin ? { ...entry, installed: true, enabled: plugin.enabled !== false } : entry;
  }), [library.entries, skills.items, installed.items]);
  const installedEntries = useMemo(() => [
    ...skills.items.map(skill => ({ ...discovered.find(entry => entry.skill_id === skill.id), ...skill, id: `skill:${skill.id}`, skill_id: skill.id, kind: 'skill', installed: true, source: skill.source || skill.path, category: skill.category || 'workflow', compatibility: 'SKILL.md', catalog_name: skill.builtin ? 'Forge starters' : skill.plugin_id ? installed.items.find(item => item.id === skill.plugin_id)?.name || 'Plugin skill' : skill.scope === 'project' ? 'Project skills' : 'Your skills' } as LibraryEntry)),
    ...installed.items.map(plugin => ({ ...discovered.find(entry => entry.plugin_id === plugin.id), ...plugin, id: `plugin:${plugin.id || plugin.name}`, plugin_id: plugin.id, kind: 'plugin', installed: true, enabled: plugin.enabled !== false, category: discovered.find(entry => entry.plugin_id === plugin.id)?.category || 'workflow', catalog_name: 'Your plugins' } as LibraryEntry)),
  ], [skills.items, installed.items, discovered]);
  const entries = tab === 'discover' ? discovered : installedEntries;
  const categories = [...new Set(entries.map(entry => entry.category?.toLocaleLowerCase()).filter((value): value is string => Boolean(value)))].sort();
  const visible = filterLibraryEntries(entries, query, kind, category, bundle);
  const refreshing = loading || installed.loading || skills.loading;
  const activeCount = installedEntries.filter(entry => entry.enabled !== false).length;
  const currentDetail = detail ? entries.find(entry => entry.id === detail.id) || entries.find(entry => entry.kind === detail.kind && ((detail.skill_id && entry.skill_id === detail.skill_id) || (detail.plugin_id && entry.plugin_id === detail.plugin_id))) || detail : null;

  async function refreshAll(remote = false) { await Promise.all([installed.refresh(), skills.refresh(), discover(remote)]); }
  async function toggle(entry: LibraryEntry, enabled: boolean, automatic = entry.automatic !== false) {
    if (pending.includes(entry.id)) return; setPending(items => [...items, entry.id]);
    try {
      if (entry.kind === 'skill' && entry.skill_id) await api('skill_toggle', { id: entry.skill_id, enabled, automatic, project_id: projectId || undefined });
      else if (entry.plugin_id) await api('plugin_toggle', { id: entry.plugin_id, enabled });
      else throw new Error('Install this item before enabling it.');
      await refreshAll();
    } catch (e) { notify(errorText(e)); } finally { setPending(items => items.filter(id => id !== entry.id)); }
  }
  async function openDetails(entry: LibraryEntry) {
    const request = ++previewGeneration.current; setDetail(entry); setPreview(''); setPreviewError(''); setPreviewBusy(entry.kind === 'skill' && Boolean(entry.skill_id));
    if (entry.kind !== 'skill' || !entry.skill_id) return;
    try { const result = await api<{ text: string }>('skill_preview', { id: entry.skill_id, project_id: projectId || undefined }); if (request === previewGeneration.current) setPreview(result.text.replace(/^---\r?\n[\s\S]*?\r?\n---(?:\r?\n|$)/, '')); }
    catch (e) { if (request === previewGeneration.current) setPreviewError(errorText(e)); }
    finally { if (request === previewGeneration.current) setPreviewBusy(false); }
  }
  function closeDetails() { previewGeneration.current++; setDetail(null); }
  async function discard() { if (inspection?.inspection_id) await api('plugin_discard', { inspection_id: inspection.inspection_id }).catch(() => {}); setInspection(null); }
  function closeImport() { if (busy) return; void discard(); setImporting(false); }
  async function inspect() { setBusy(true); setError(''); await discard(); try { setInspection(await api<Inspection>('plugin_inspect', { source })); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function install() { setBusy(true); setError(''); try { await api('plugin_install', { inspection_id: inspection?.inspection_id, source, reviewed: true }); setImporting(false); setInspection(null); await refreshAll(); notify('Plugin installed. Tool connections remain disabled until you configure them.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  function beginImport(value = '') { void discard(); setSource(value); setError(''); setImporting(true); }
  async function addCatalog() { setCatalogBusy(true); setCatalogError(''); try { await api('catalog_save', { name: catalogName, source: catalogSource }); setCatalogName(''); setCatalogSource(''); await discover(true); notify('Library source added.'); } catch (e) { setCatalogError(errorText(e)); } finally { setCatalogBusy(false); } }
  async function addSkill() { setSkillImportBusy(true); setSkillImportError(''); try { await api('skill_install', { source: skillSource, project_id: projectId || undefined }); setAddingSkill(false); setSkillSource(''); await refreshAll(); notify('Skill imported.'); } catch (e) { setSkillImportError(errorText(e)); } finally { setSkillImportBusy(false); } }

  function card(entry: LibraryEntry) {
    const isPending = pending.includes(entry.id); const enabled = entry.enabled !== false;
    return <article className={`library-card ${entry.builtin ? 'starter' : ''}`} key={entry.id}>
      <div className="library-card-top"><div className={`library-symbol ${entry.kind === 'skill' ? 'skill' : 'plugin'}`}><SkillIcon category={entry.category} kind={entry.kind} /></div><span className="library-kind">{kindLabel(entry.kind)}</span>{entry.installed && <Badge tone={enabled ? 'accent' : ''}>{enabled ? <><Check size={10} />On</> : 'Off'}</Badge>}</div>
      <button className="library-card-title" onClick={() => void openDetails(entry)}><h2>{entry.name}</h2><ChevronRight size={14} /></button>
      <p>{entry.description || 'A portable extension for your Forge workspace.'}</p>
      <div className="library-card-tags">{entry.category && <span>{categoryLabel(entry.category)}</span>}{entry.builtin && <span><ShieldCheck size={11} />Forge starter</span>}{!entry.builtin && entry.catalog_name && <span title={entry.catalog_name}>{entry.catalog_name}</span>}</div>
      <small className="library-card-support">{entry.license || 'Review license'}<span>·</span>{entry.builtin ? 'No extra setup' : 'Review compatibility'}</small>
      <footer><button className="text-button" onClick={() => void openDetails(entry)}>{entry.kind === 'skill' ? 'View skill' : 'View details'}<ArrowUpRight size={12} /></button>{entry.installed ? <LibrarySwitch name={`Enable ${entry.name}`} label={enabled ? 'On' : 'Off'} value={enabled} disabled={isPending} change={value => void toggle(entry, value)} /> : <button className="secondary" disabled={!entry.source} onClick={() => beginImport(entry.source)}>Review & install</button>}</footer>
      {tab === 'installed' && entry.kind === 'skill' && <div className="library-auto"><LibrarySwitch name={`Automatically use ${entry.name}`} label="Use when relevant" value={entry.automatic !== false} disabled={!enabled || isPending} change={value => void toggle(entry, enabled, value)} /></div>}
    </article>;
  }

  return <div className="library-page">
    <PageHeader title="Library" subtitle="Useful skills and tools, ready for your workspace."><button className="secondary" onClick={() => { setSkillImportError(''); setAddingSkill(true); }}><BookOpen size={14} />Add skill</button><button className="primary" onClick={() => beginImport()}><Plus size={14} />Import plugin</button></PageHeader>
    <div className="library-nav"><div className="section-tabs" aria-label="Library views"><button className={tab === 'discover' ? 'active' : ''} aria-pressed={tab === 'discover'} onClick={() => { setTab('discover'); setCategory(''); }}><Compass size={15} />Discover</button><button className={tab === 'installed' ? 'active' : ''} aria-pressed={tab === 'installed'} onClick={() => { setTab('installed'); setCategory(''); }}><Package size={15} />Installed<span>{installedEntries.length}</span></button></div><button className="text-button" onClick={() => setSourcesOpen(true)}><SlidersHorizontal size={14} />Library sources</button></div>
    <div className="library-search-row"><div className="search-input"><Search size={17} /><input value={query} onChange={e => setQuery(e.target.value)} aria-label="Search library" placeholder="Search skills, plugins and connected libraries…" />{query && <button className="text-button" aria-label="Clear library search" onClick={() => setQuery('')}>Clear</button>}</div><IconButton label="Refresh library" disabled={refreshing} onClick={() => void refreshAll(true)}><RefreshCw size={16} className={refreshing ? 'spin' : ''} /></IconButton></div>
    <div className="library-filters"><label className="library-bundle-filter">Workflow bundle<select aria-label="Workflow bundle" value={bundle} onChange={e => setBundle(e.target.value)}><option value="">All bundles</option>{[["build","Build and architecture"],["design","Design and frontend"],["backend","Backend and data"],["review","Code quality"],["research","Research essentials"],["delivery","Delivery and reuse"]].map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><div className="library-types" aria-label="Extension type">{([['all', 'All'], ['skill', 'Skills'], ['plugin', 'Plugins']] as const).map(([value, label]) => <button key={value} aria-pressed={kind === value} className={kind === value ? 'active' : ''} onClick={() => setKind(value)}>{label}</button>)}</div><span className="library-filter-divider" /><div className="library-categories" aria-label="Skill categories"><button className={!category ? 'active' : ''} aria-pressed={!category} onClick={() => setCategory('')}>All categories</button>{categories.map(value => <button key={value} className={category === value ? 'active' : ''} aria-pressed={category === value} onClick={() => setCategory(value)}>{categoryLabel(value)}</button>)}</div></div>
    {discoveryError && tab === 'discover' && <ErrorNotice error={discoveryError} retry={() => void discover(true)} />}
    {tab === 'installed' && installed.error && <ErrorNotice error={installed.error} retry={() => void installed.refresh()} />}{tab === 'installed' && skills.error && <ErrorNotice error={skills.error} retry={() => void skills.refresh()} />}
    {tab === 'discover' && library.sources.some(item => item.error) && <div className="library-source-notice"><Globe size={14} /><span>Some library sources are unavailable. Available items are shown below.</span><button className="text-button" onClick={() => setSourcesOpen(true)}>View sources</button></div>}
    <div className="library-section-header"><div><h2>{query ? `Results for “${query}”` : tab === 'installed' ? 'Your collection' : 'Discover your next workflow'}</h2><p>{tab === 'installed' ? `${activeCount} enabled · Skills can be used explicitly or when relevant.` : 'Searches Forge starters and your supported library sources automatically.'}</p></div><span aria-live="polite">{visible.length} {visible.length === 1 ? 'item' : 'items'}</span></div>
    {loading && !library.entries.length && tab === 'discover' ? <div className="library-loading" role="status"><LoaderCircle size={19} className="spin" />Loading your library…</div> : visible.length ? <div className="library-grid">{visible.map(card)}</div> : <Empty icon={<Search size={27} />} title={query || kind !== 'all' || category || bundle ? 'No matching items' : tab === 'installed' ? 'Start your collection' : 'No library items available'} text={query || kind !== 'all' || category || bundle ? 'Try a different search or clear your filters.' : tab === 'installed' ? 'Discover a starter skill, or import a portable plugin.' : 'Refresh your library or add a supported catalog source.'} action={query || kind !== 'all' || category || bundle ? <button className="secondary" onClick={() => { setQuery(''); setKind('all'); setCategory(''); setBundle(''); }}>Clear filters</button> : <button className="secondary" onClick={() => tab === 'installed' ? setTab('discover') : void discover(true)}>{tab === 'installed' ? 'Browse Discover' : 'Refresh library'}</button>} />}
    <p className="library-footnote"><ShieldCheck size={13} />Skills guide the agent. Your permission settings still control every action.</p>

    {currentDetail && <Modal title={currentDetail.name} close={closeDetails} wide><div className="library-detail-heading"><div className="library-symbol skill"><SkillIcon category={currentDetail.category} kind={currentDetail.kind} size={25} /></div><div><p>{currentDetail.description}</p><div className="library-detail-badges"><Badge>{kindLabel(currentDetail.kind)}</Badge>{currentDetail.category && <Badge>{categoryLabel(currentDetail.category)}</Badge>}{currentDetail.builtin && <Badge tone="accent">Forge starter</Badge>}</div></div></div><dl className="library-detail-metadata"><div><dt>Source</dt><dd>{currentDetail.catalog_name || currentDetail.source_name || 'Imported locally'}</dd></div><div><dt>Compatibility</dt><dd>{currentDetail.compatibility || (currentDetail.kind === 'skill' ? 'SKILL.md' : 'Review required')}</dd></div><div><dt>License</dt><dd>{currentDetail.license || 'Shown during import review'}</dd></div>{currentDetail.version && <div><dt>Version</dt><dd>{currentDetail.version}</dd></div>}</dl>{currentDetail.setup && <p className="library-setup-note">{Array.isArray(currentDetail.setup) ? currentDetail.setup.join(' · ') : currentDetail.setup}</p>}{currentDetail.installed && <div className="library-detail-controls"><LibrarySwitch name={`Enable ${currentDetail.name} in details`} label="Enabled" value={currentDetail.enabled !== false} disabled={pending.includes(currentDetail.id)} change={value => void toggle(currentDetail, value)} />{currentDetail.kind === 'skill' && <LibrarySwitch name={`Automatically use ${currentDetail.name} in details`} label="Use when relevant" value={currentDetail.automatic !== false} disabled={currentDetail.enabled === false || pending.includes(currentDetail.id)} change={value => void toggle(currentDetail, currentDetail.enabled !== false, value)} />}</div>}{previewBusy && <div className="library-loading" role="status"><LoaderCircle size={16} className="spin" />Reading skill…</div>}{previewError && <ErrorNotice error={previewError} retry={() => void openDetails(currentDetail)} />}{preview && <details className="library-instructions" open><summary><BookOpen size={14} />Skill instructions</summary><Markdown text={preview} /></details>}<footer><button className="subtle" onClick={closeDetails}>Close</button>{currentDetail.kind === "skill" && currentDetail.skill_id && <button className="secondary" onClick={() => { const id = currentDetail.skill_id!; closeDetails(); setWorkbench(id); }}>Open workbench</button>}{currentDetail.kind === 'plugin' && currentDetail.installed && currentDetail.source && <button className="secondary" onClick={() => { closeDetails(); beginImport(currentDetail.source); }}>Review update</button>}{!currentDetail.installed && currentDetail.source && <button className="primary" onClick={() => { closeDetails(); beginImport(currentDetail.source); }}>Review & install</button>}</footer></Modal>}
    {workbench && <SkillWorkbench id={workbench} projectId={projectId} close={() => setWorkbench(null)} onSaved={refreshAll} notify={notify} />}
    {importing && <Modal title="Import plugin" close={closeImport} wide><Field label="Source" hint="A local folder or ZIP, GitHub repository URL, or linked catalog entry."><input autoFocus value={source} disabled={busy} onChange={e => { void discard(); setSource(e.target.value); setError(''); }} placeholder="https://github.com/owner/plugin" /></Field>{inspection && <div className="plugin-review"><header><h3>{inspection.name}</h3><Badge>{inspection.format || 'Portable'}</Badge>{inspection.version && <small>{inspection.version}</small>}</header>{inspection.description && <p>{inspection.description}</p>}<p>{inspection.compatibility}</p>{inspection.features && <div className="inspection-features">{Object.entries(inspection.features).map(([key, value]) => <span key={key}>{key.replace(/_/g, ' ')} <strong>{Array.isArray(value) ? value.length : String(value)}</strong></span>)}</div>}{inspection.warnings?.length ? <div className="inspection-warnings">{inspection.warnings.map((warning, index) => <p key={index}>{warning}</p>)}</div> : null}{inspection.licenses?.length ? <small>License files retained: {inspection.licenses.join(', ')}</small> : <small>No license file found in this bundle.</small>}{!inspection.compatible && <ErrorNotice error="This bundle has no compatible portable skills or MCP components. It needs a Forge adapter." />}</div>}{error && <ErrorNotice error={error} />}<footer><button className="subtle" disabled={busy} onClick={closeImport}>Cancel</button>{inspection ? <button className="primary" disabled={busy || !inspection.compatible} onClick={() => void install()}>{busy ? 'Installing…' : 'Install reviewed plugin'}</button> : <button className="primary" disabled={!source.trim() || busy} onClick={() => void inspect()}>{busy ? 'Inspecting…' : 'Inspect source'}</button>}</footer></Modal>}
    {sourcesOpen && <Modal title="Library sources" close={() => { if (!catalogBusy) setSourcesOpen(false); }} wide><p className="muted">Discover searches these sources together. Refresh checks catalog metadata; installing a plugin always requires review.</p><div className="library-sources">{library.sources.map(item => <article key={item.id}><Globe size={17} /><div><strong>{item.name}</strong><small>{item.error || (item.builtin || item.id === 'forge-starter' || item.source === 'builtin' ? 'Included with Forge' : 'Supported catalog · review before install')}</small></div><Badge tone={item.error ? '' : 'accent'}>{item.error ? 'Unavailable' : item.state === 'cached' || item.status === 'cached' ? 'Cached' : 'Ready'}</Badge>{item.count !== undefined && <span>{item.count} items</span>}</article>)}</div><form className="library-source-form" onSubmit={e => { e.preventDefault(); void addCatalog(); }}><h3>Add a source</h3><Field label="Name"><input required disabled={catalogBusy} value={catalogName} onChange={e => setCatalogName(e.target.value)} placeholder="My team library" /></Field><Field label="Catalog source" hint="An HTTPS catalog JSON URL or local catalog path."><input required disabled={catalogBusy} value={catalogSource} onChange={e => setCatalogSource(e.target.value)} placeholder="https://example.com/catalog.json" /></Field>{catalogError && <ErrorNotice error={catalogError} />}<footer><button className="primary" disabled={catalogBusy}>{catalogBusy ? 'Adding…' : 'Add catalog'}</button></footer></form></Modal>}
    {addingSkill && <Modal title="Add skill" close={() => { if (!skillImportBusy) setAddingSkill(false); }}><form onSubmit={e => { e.preventDefault(); void addSkill(); }}><Field label="Source" hint="A folder or ZIP containing SKILL.md, or a GitHub repository URL."><input autoFocus required disabled={skillImportBusy} value={skillSource} onChange={e => setSkillSource(e.target.value)} /></Field>{skillImportError && <ErrorNotice error={skillImportError} />}<footer><button type="button" className="subtle" disabled={skillImportBusy} onClick={() => setAddingSkill(false)}>Cancel</button><button className="primary" disabled={skillImportBusy}>{skillImportBusy ? 'Importing…' : 'Import skill'}</button></footer></form></Modal>}
  </div>;
}
