import { useState } from 'react';
import { ClipboardList, Globe, Plug, Plus, ShieldCheck } from 'lucide-react';
import { api, errorText } from './api';
import { Badge, Empty, ErrorNotice, Field, Markdown, Modal, PageHeader, Toggle, useResource } from './components';
import type { Plugin } from './types';
interface Skill { id: string; name: string; description?: string; path?: string; scope?: string; enabled: boolean; automatic: boolean; }
interface Catalog { id: string; name: string; source?: string; reviewed?: boolean; entries: Plugin[]; }
interface Inspection { inspection_id?: string; name: string; description?: string; version?: string; format?: string; compatibility?: string; warnings?: string[]; licenses?: string[]; compatible: boolean; features?: Record<string, unknown>; }
export function PluginsPage({ notify, projectId }: { notify: (message: string) => void; projectId?: string | null }) {
  const installed = useResource<Plugin>('plugins', 'plugins'); const catalogs = useResource<Catalog>('catalogs', 'catalogs'); const skills = useResource<Skill>('skills', 'skills', { project_id: projectId || undefined });
  const [tab, setTab] = useState('installed'); const [importing, setImporting] = useState(false); const [source, setSource] = useState(''); const [inspection, setInspection] = useState<Inspection | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [catalog, setCatalog] = useState(false); const [catalogName, setCatalogName] = useState(''); const [catalogSource, setCatalogSource] = useState(''); const [skillSource, setSkillSource] = useState(''); const [addingSkill, setAddingSkill] = useState(false); const [preview, setPreview] = useState<{ name: string; text: string } | null>(null);
  async function discard() { if (inspection?.inspection_id) await api('plugin_discard', { inspection_id: inspection.inspection_id }).catch(() => {}); setInspection(null); }
  function closeImport() { void discard(); setImporting(false); }
  async function inspect() { setBusy(true); setError(''); await discard(); try { setInspection(await api<Inspection>('plugin_inspect', { source })); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function install() { setBusy(true); setError(''); try { await api('plugin_install', { inspection_id: inspection?.inspection_id, source, reviewed: true }); setImporting(false); setInspection(null); await installed.refresh(); await skills.refresh(); notify('Plugin installed. Imported MCP servers require connection setup before use.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  function beginImport(value = '') { void discard(); setSource(value); setError(''); setImporting(true); }
  return <><PageHeader title="Plugins" subtitle="Extend your workspace with portable skills and tool connections."><button className="primary" onClick={() => beginImport()}><Plus size={15} />Import plugin</button></PageHeader><div className="section-tabs"><button className={tab === 'installed' ? 'active' : ''} onClick={() => setTab('installed')}>Installed</button><button className={tab === 'catalog' ? 'active' : ''} onClick={() => setTab('catalog')}>Discover</button><button className={tab === 'skills' ? 'active' : ''} onClick={() => setTab('skills')}>Skills</button></div>
    {tab === 'installed' && <>{installed.error && <ErrorNotice error={installed.error} retry={() => void installed.refresh()} />}{installed.items.length ? <div className="card-grid">{installed.items.map((plugin, index) => <article className="plugin-card" key={plugin.id || index}><div className="plugin-card-top"><Plug size={25} /><Badge>{plugin.enabled === false ? 'Disabled' : 'Installed'}</Badge></div><h2>{plugin.name}</h2><p>{plugin.description}</p><small>{plugin.compatibility}</small>{plugin.version && <small className="plugin-version">v{plugin.version}</small>}<footer><button className="text-button" onClick={() => void api('plugin_toggle', { id: plugin.id, enabled: plugin.enabled === false }).then(() => { void installed.refresh(); void skills.refresh(); }).catch(e => notify(errorText(e)))}>{plugin.enabled === false ? 'Enable' : 'Disable'}</button><button className="text-button" onClick={() => beginImport(plugin.source)}>Review update</button></footer></article>)}</div> : !installed.error && !installed.loading && <Empty icon={<Plug size={29} />} title="Your extensions belong here" text="Discover a starter workflow or import a portable plugin from a folder, ZIP or GitHub repository." />}</>}
    {tab === 'catalog' && <><div className="catalog-toolbar"><span className="muted">Choose a source and review compatibility before installing.</span><button className="secondary" onClick={() => setCatalog(true)}><Globe size={14} />Add catalog</button></div>{catalogs.error && <ErrorNotice error={catalogs.error} retry={() => void catalogs.refresh()} />}{catalogs.items.map(item => <section className="catalog-section" key={item.id}><h2>{item.name}{item.reviewed && <Badge><ShieldCheck size={10} />Reviewed starter</Badge>}</h2><div className="card-grid">{item.entries.map((plugin, index) => <article className="plugin-card" key={index}><Plug size={23} /><h2>{plugin.name}</h2><p>{plugin.description}</p><footer><button className="secondary" onClick={() => beginImport(plugin.source)}>Review & install</button></footer></article>)}</div></section>)}</>}
    {tab === 'skills' && <><div className="catalog-toolbar"><span className="muted">Global and project skills remain subject to your permission profile.</span><button className="secondary" onClick={() => setAddingSkill(true)}><Plus size={14} />Add skill</button></div>{skills.error && <ErrorNotice error={skills.error} retry={() => void skills.refresh()} />}{skills.items.length ? <div className="stack">{skills.items.map(skill => <article className="skill-card" key={skill.id}><div className="skill-heading"><ClipboardList size={18} /><button className="text-button" disabled={!skill.enabled} onClick={() => void api<{ text: string }>('skill_read', { id: skill.id, project_id: projectId || undefined }).then(result => setPreview({ name: skill.name, text: result.text })).catch(e => notify(errorText(e)))}>{skill.name}</button><Badge>{skill.scope}</Badge></div><p>{skill.description}</p><small>{skill.path}</small><div className="skill-toggles"><Toggle label={`Enable ${skill.name}`} checked={skill.enabled} onChange={enabled => void api('skill_toggle', { id: skill.id, enabled, automatic: skill.automatic }).then(() => void skills.refresh()).catch(e => notify(errorText(e)))} /><Toggle label={`Automatically use ${skill.name}`} checked={skill.automatic} disabled={!skill.enabled} onChange={automatic => void api('skill_toggle', { id: skill.id, enabled: skill.enabled, automatic }).then(() => void skills.refresh()).catch(e => notify(errorText(e)))} /></div></article>)}</div> : !skills.error && !skills.loading && <Empty icon={<ClipboardList size={27} />} title="Give agents useful instructions" text="Install a plugin with SKILL.md files, or import a skill folder." />}</>}
    {importing && <Modal title="Import plugin" close={closeImport} wide><Field label="Source" hint="A local folder or ZIP, GitHub repository URL, or linked catalog entry."><input autoFocus value={source} disabled={busy} onChange={e => { void discard(); setSource(e.target.value); setError(''); }} placeholder="https://github.com/owner/plugin" /></Field>{inspection && <div className="plugin-review"><header><h3>{inspection.name}</h3><Badge>{inspection.format || 'Portable'}</Badge>{inspection.version && <small>{inspection.version}</small>}</header>{inspection.description && <p>{inspection.description}</p>}<p>{inspection.compatibility}</p>{inspection.features && <div className="inspection-features">{Object.entries(inspection.features).map(([key, value]) => <span key={key}>{key.replace(/_/g, ' ')} <strong>{Array.isArray(value) ? value.length : String(value)}</strong></span>)}</div>}{inspection.warnings?.length ? <div className="inspection-warnings">{inspection.warnings.map((warning, index) => <p key={index}>{warning}</p>)}</div> : null}{inspection.licenses?.length ? <small>License files retained: {inspection.licenses.join(', ')}</small> : <small>No license file found in this bundle.</small>}{!inspection.compatible && <ErrorNotice error="This bundle has no compatible portable skills or MCP components. It needs a Forge adapter." />}</div>}{error && <ErrorNotice error={error} />}<footer><button className="subtle" disabled={busy} onClick={closeImport}>Cancel</button>{inspection ? <button className="primary" disabled={busy || !inspection.compatible} onClick={() => void install()}>{busy ? 'Installing…' : 'Install reviewed plugin'}</button> : <button className="primary" disabled={!source.trim() || busy} onClick={() => void inspect()}>{busy ? 'Inspecting…' : 'Inspect source'}</button>}</footer></Modal>}
    {catalog && <Modal title="Add external catalog" close={() => setCatalog(false)}><form onSubmit={e => { e.preventDefault(); void api('catalog_save', { name: catalogName, source: catalogSource }).then(() => { setCatalog(false); void catalogs.refresh(); }).catch(e => notify(errorText(e))); }}><Field label="Name"><input autoFocus required value={catalogName} onChange={e => setCatalogName(e.target.value)} /></Field><Field label="Catalog source" hint="An HTTPS catalog JSON URL or local catalog path."><input required value={catalogSource} onChange={e => setCatalogSource(e.target.value)} /></Field><footer><button className="primary">Add catalog</button></footer></form></Modal>}
    {addingSkill && <Modal title="Add skill" close={() => setAddingSkill(false)}><form onSubmit={e => { e.preventDefault(); void api('skill_install', { source: skillSource, project_id: projectId || undefined }).then(() => { setAddingSkill(false); void skills.refresh(); notify('Skill imported.'); }).catch(e => notify(errorText(e))); }}><Field label="Source" hint="A folder or ZIP containing SKILL.md, or a GitHub repository URL."><input autoFocus required value={skillSource} onChange={e => setSkillSource(e.target.value)} /></Field><footer><button className="primary">Import skill</button></footer></form></Modal>}
    {preview && <Modal title={preview.name} close={() => setPreview(null)} wide><Markdown text={preview.text} /></Modal>}
  </>;
}
