import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import { MoreHorizontal, Trash2 } from 'lucide-react';
import { api, errorText } from './api';
import { ErrorNotice, Modal } from './components';
import type { Project } from './types';
export function ProjectActions({ project, children, onRemoved }: { project: Project; children: React.ReactNode; onRemoved: (id: string) => Promise<void> }) {
  const [menu, setMenu] = useState(false); const [confirm, setConfirm] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [position, setPosition] = useState({ top: 0, left: 0 });
  const root = useRef<HTMLDivElement>(null); const menuRef = useRef<HTMLDivElement>(null); const trigger = useRef<HTMLButtonElement>(null);
  useEffect(() => { if (!menu) return; menuRef.current?.querySelector<HTMLButtonElement>('button')?.focus(); const click = (event: MouseEvent) => { if (!root.current?.contains(event.target as Node) && !menuRef.current?.contains(event.target as Node)) setMenu(false); }; const keys = (event: KeyboardEvent) => { if (event.key === 'Escape') { setMenu(false); trigger.current?.focus(); } }; document.addEventListener('mousedown', click); document.addEventListener('keydown', keys); return () => { document.removeEventListener('mousedown', click); document.removeEventListener('keydown', keys); }; }, [menu]);
  function open(x: number, y: number) { setPosition({ left: Math.max(8, Math.min(window.innerWidth - 220, x)), top: Math.max(8, Math.min(window.innerHeight - 80, y)) }); setMenu(true); }
  async function remove() { setBusy(true); setError(''); try { await api('project_delete', { id: project.id }); await onRemoved(project.id); setConfirm(false); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <div className="project-with-actions" ref={root} onContextMenu={event => { event.preventDefault(); open(event.clientX, event.clientY); }}>{children}<button className="project-actions-trigger" ref={trigger} aria-label={`Project actions for ${project.name}`} aria-haspopup="menu" aria-expanded={menu} title="Project actions" onClick={() => { const rect = trigger.current?.getBoundingClientRect(); if (rect) open(rect.right - 210, rect.bottom + 4); }}><MoreHorizontal size={14} /></button>{menu && createPortal(<div className="chat-actions-menu" role="menu" aria-label={`Project actions for ${project.name}`} style={position} ref={menuRef}><button className="menu-danger" role="menuitem" onClick={() => { setMenu(false); setConfirm(true); setError(''); }}><Trash2 size={14} />Delete project</button></div>, document.body)}{confirm && <Modal title="Remove project registration?" close={() => { if (!busy) setConfirm(false); }}><p>Remove <strong>{project.name}</strong> from Forge? The project folder and its files will stay on disk. Conversations move to Unassigned chats.</p>{error && <ErrorNotice error={error} />}<footer><button className="subtle" disabled={busy} onClick={() => setConfirm(false)}>Cancel</button><button className="danger-button" disabled={busy} onClick={() => void remove()}>{busy ? 'Removing…' : 'Remove project'}</button></footer></Modal>}</div>;
}
