import { useState } from 'react';
import { ShieldAlert } from 'lucide-react';
import { api, errorText } from './api';
import { ErrorNotice, Field, Modal, useResource } from './components';
interface UnknownAction { id: string; name: string; arguments: string | Record<string, unknown>; status: string; }
export function RecoveryPanel({ runId, recovery, notify }: { runId: string; recovery?: string; notify: (message: string) => void }) {
  const data = useResource<UnknownAction>('unknown_actions', 'actions', { run_id: runId }); const [action, setAction] = useState<UnknownAction | null>(null); const [evidence, setEvidence] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  async function resolve(outcome: string) { if (!action) return; setBusy(true); try { await api('resolve_action', { invocation_id: action.id, outcome, evidence }); setAction(null); await data.refresh(); notify('Inspection recorded. Resume when you are ready.'); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  return <>{recovery && <p className="recovery-note">{recovery}</p>}{data.items.map(item => <button className="recovery-action" key={item.id} onClick={() => { setAction(item); setEvidence(''); setError(''); }}><ShieldAlert size={13} /><span>Inspect {item.name}</span></button>)}{data.error && <ErrorNotice error={data.error} />}{action && <Modal title="Inspect an interrupted action" close={() => setAction(null)} wide><p className="muted">Forge cannot verify whether this action finished. Inspect the affected files, app or command output before recording its outcome. This action will not be repeated automatically.</p><strong>{action.name}</strong><pre className="inspection-arguments">{typeof action.arguments === 'string' ? action.arguments : JSON.stringify(action.arguments, null, 2)}</pre><Field label="Inspection evidence"><textarea autoFocus rows={4} value={evidence} onChange={e => setEvidence(e.target.value)} placeholder="What did you inspect, and what confirms the outcome?" /></Field>{error && <ErrorNotice error={error} />}<footer><button className="secondary" disabled={!evidence.trim() || busy} onClick={() => void resolve('not_executed')}>Verified not executed</button><button className="primary" disabled={!evidence.trim() || busy} onClick={() => void resolve('completed')}>Verified completed</button></footer></Modal>}</>;
}
