import { useEffect, useState } from 'react';
import { Activity, BookOpen, Search, Sparkles } from 'lucide-react';
import { api, errorText } from './api';
import { Badge, ToolCard } from './components';
import type { PhaseTiming, RunEvent, RunContextSnapshot, VerificationFeedback } from './types';
import './runInspector.css';

export function ActivityCard({ event }: { event: RunEvent }) {
  if (event.type === 'verification') return <article className="instruction-activity"><Activity size={15}/><div><strong>{event.passed === true ? 'Checks passed' : 'Checks failed'}</strong><p>{event.passed === true ? 'The previously failed checks now have passing evidence.' : `${Number(event.failed_count || 1)} failed checks recorded. Inspect the run for details.`}</p></div><Badge>{event.passed === true ? 'Passed' : 'Failed'}</Badge></article>;
  if (event.type === 'progress_nudge') return <article className="instruction-activity"><Activity size={15}/><div><strong>Repeated read detected</strong><p>The agent was prompted to use existing evidence and advance the task.</p></div></article>;
  if (event.type === 'skill') return <article className="instruction-activity"><BookOpen size={15} /><div><strong>{event.name || 'Skill activated'}</strong><p>{String(event.reason || event.selection_reason || 'Selected for this task')}</p>{Boolean(event.digest) && <small>Revision {String(event.digest).slice(0, 8)}</small>}</div><Badge>Skill</Badge></article>;
  if (event.type === 'specialist') return <article className="instruction-activity"><Sparkles size={15} /><div><strong>{String(event.specialty || 'Cloud specialist')}</strong><p>{event.text || String(event.state || '')}</p></div><Badge>{event.state || 'Advisory'}</Badge></article>;
  if (event.type === 'context_snapshot' || event.type === 'tool_selection') return <article className="instruction-activity"><Activity size={15} /><div><strong>{event.type === 'tool_selection' ? 'Tools selected' : 'Context prepared'}</strong><p>{event.text || 'Relevant instructions and evidence prepared for this round.'}</p></div></article>;
  return <ToolCard event={event} />;
}

interface Diagnostics { workflow_stage?: string; phase?: string; status?: string; checkpoint?: string; tools?: string[]; skills?: string[]; context_snapshot?: RunContextSnapshot; verification?: VerificationFeedback | null; invocations?: {id:string;name:string;status:string}[]; usage?: {requests:{id:string;phase_timings:PhaseTiming;token_breakdown:Record<string,number>}[]}; }
const seconds = (n?: number | null) => typeof n === 'number' ? `${n.toFixed(2)} s` : 'Unavailable';
export function RunInspector({ runId }: { runId: string }) {
  const [open,setOpen]=useState(false); const [data,setData]=useState<Diagnostics|null>(null); const [error,setError]=useState('');
  useEffect(() => { if (!open) return; let alive=true,pending=false; const refresh=async()=>{if(pending || document.visibilityState==='hidden')return;pending=true;try { const value=await api<Diagnostics>('run_context_inspect',{run_id:runId}); if(alive){setData(value);setError('');} }catch(e){if(alive)setError(errorText(e));}finally{pending=false;}}; void refresh(); const timer=setInterval(()=>void refresh(),5000); document.addEventListener('visibilitychange',refresh); return()=>{alive=false;clearInterval(timer);document.removeEventListener('visibilitychange',refresh);}; },[open,runId]);
  const request=data?.usage?.requests?.[0]; const breakdown=request?.token_breakdown || data?.context_snapshot?.token_breakdown || {};
  return <div className="run-inspector"><button className="text-button" onClick={()=>setOpen(!open)} aria-expanded={open}><Search size={13}/>Inspect run</button>{open && <div className="run-inspector-body">{error && <p role="alert">{error}</p>}<p><Badge>{data?.workflow_stage || data?.phase || data?.status || 'Loading'}</Badge></p><dl>{Object.entries(breakdown).filter(([, value]) => typeof value === 'number').map(([name,value])=><div key={name}><dt>{name.replaceAll('_',' ')}</dt><dd>{Number(value).toLocaleString()} estimated tokens</dd></div>)}</dl>{request && <dl>{(['queue_seconds','load_seconds','prefill_seconds','first_output_seconds','decode_seconds','total_seconds'] as const).map(name=><div key={name}><dt>{name.replace('_seconds','').replaceAll('_',' ')}</dt><dd>{seconds(request.phase_timings[name])}</dd></div>)}</dl>}<details><summary>Active skills ({data?.skills?.length || 0})</summary><p>{data?.skills?.join(', ') || 'No skill snapshot saved.'}</p></details><details><summary>Selected tools ({data?.tools?.length || 0})</summary><p>{data?.tools?.join(', ') || 'No tool snapshot saved.'}</p></details><details><summary>Invocation outcomes ({data?.invocations?.length || 0})</summary>{data?.invocations?.map(item=><p key={item.id}>{item.name} · {item.status}</p>)}</details>{data?.verification && <details open><summary>Unresolved checks ({data.verification.scope_count})</summary><p>{data.verification.changed_since_check ? 'Files have changed. These checks need fresh evidence.' : 'These checks do not yet have passing evidence.'}</p>{data.verification.failures.map((failure,index)=><div key={failure.invocation_id || `${failure.tool}-${index}`}><strong>{failure.tool}</strong>{failure.failed.map((check,i)=><p key={i}>{check.name}{check.detail && <small> · {check.detail}</small>}</p>)}</div>)}</details>}{data?.checkpoint && <p className="muted">{data.checkpoint}</p>}</div>}</div>;
}
