import { useEffect, useState } from 'react';
import { Download, RefreshCw, ShieldCheck } from 'lucide-react';
import { api, errorText, isNative } from './api';
import { Badge, ErrorNotice } from './components';
interface Update { state?: string; current_version: string; automatic_install_available: boolean; signing_setup_required: boolean; message: string; release?: { version: string; size: number }; verified?: boolean; error?: string; received_bytes?: number; operation_id?: string; }
export function UpdateSettings({ notify }: { notify: (v: string) => void }) {
  const [status, setStatus] = useState<Update>(); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  async function refresh() { try { setStatus(await api<Update>('update_status')); } catch (e) { setError(errorText(e)); } }
  useEffect(() => { void refresh(); const t = setInterval(() => void refresh(), 1500); return () => clearInterval(t); }, []);
  async function action(name: string) { setBusy(true); setError(''); try { const r = await api<Update & { prepared?: boolean }>(name); if (r.prepared) notify('Forge is closing to apply the verified update. Your data backup is retained.'); else setStatus(r); } catch (e) { setError(errorText(e)); } finally { setBusy(false); } }
  async function diagnostics() { try { const r = await api<{ diagnostics: unknown }>('diagnostics_export'); const blob = new Blob([JSON.stringify(r.diagnostics, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const anchor = document.createElement('a'); anchor.href = url; anchor.download = 'forge-diagnostics.json'; anchor.click(); URL.revokeObjectURL(url); notify('Diagnostics contain versions, counts and settings, with no conversations or private paths.'); } catch (e) { setError(errorText(e)); } }
  return <><h2>Updates & diagnostics</h2><section className="settings-card"><div className="setting-row"><div><strong>Forge {status?.current_version || '4.2.2'}</strong><small>MIT licensed · Local AI workspace</small></div><Badge>{status?.state || 'Ready'}</Badge></div><p className="muted">{status?.message}</p>{status?.release && <p>Version {status.release.version} is available.</p>}{(error || status?.error) && <ErrorNotice error={error || status?.error || ''} />}<div className="setup-actions"><button className="secondary" disabled={busy} onClick={() => void action('update_check')}><RefreshCw size={14} />Check for updates</button>{status?.release && <button className="secondary" disabled={busy || status.state === 'downloading' || !status.automatic_install_available} onClick={() => void action('update_download')}><Download size={14} />Download & verify</button>}{status?.verified && <button className="primary" disabled={busy || !isNative()} onClick={() => void action('update_apply')}><ShieldCheck size={14} />Install & restart</button>}{status?.state === 'downloading' && <button className="text-button" onClick={() => void action('update_cancel')}>Cancel</button>}{status?.operation_id && <button className="text-button" disabled={busy || !isNative()} onClick={() => void action('update_rollback')}>Roll back previous installation</button>}</div>{status?.signing_setup_required && <p className="muted">Public signing setup is pending. Automatic installation stays disabled until a trusted publisher ships a signed release.</p>}<a href="https://github.com/Bh0ps/forge-local-ai/releases" target="_blank" rel="noopener noreferrer">View public releases</a></section><h2>Share diagnostics</h2><section className="settings-card"><p className="muted">Export a small report containing app and system versions, configuration and counts. Chats, prompts, attachments, credentials, project identifiers, paths and raw logs are excluded.</p><button className="secondary" onClick={() => void diagnostics()}>Export diagnostic report</button></section></>;
}
