"""Remove generated bytecode from dependency notice directories before release."""
import argparse
from pathlib import Path

def prune(app):
    root=Path(app).resolve(strict=True)
    count=0
    for file in root.rglob('*'):
        relative=file.relative_to(root)
        if (file.is_file() and file.suffix in ('.pyc','.pyo') and
            any(part.endswith('.dist-info') for part in relative.parts) and
            'licenses' in relative.parts and '__pycache__' in relative.parts):
            if file.is_symlink() or not file.resolve().is_relative_to(root): raise ValueError('Notice cache escaped the application directory.')
            file.unlink();count+=1
    for folder in sorted(root.rglob('__pycache__'),key=lambda path:len(path.parts),reverse=True):
        relative=folder.relative_to(root)
        if 'licenses' in relative.parts and any(part.endswith('.dist-info') for part in relative.parts):
            if folder.is_symlink() or not folder.resolve().is_relative_to(root): raise ValueError('Notice cache escaped the application directory.')
            if not any(folder.iterdir()):folder.rmdir()
    return count

if __name__=='__main__':
    parser=argparse.ArgumentParser();parser.add_argument('--app',required=True)
    print('Removed',prune(parser.parse_args().app),'generated notice cache files.')
